#!/usr/bin/env bash
#A Bash script that displays listening ports:
#	That only shows listening sockets.
#	That shows the PID and name of the program to which each socket belong.

netstat -tupln | awk 'NR>1 {print $1, $4, $5, $6, $7}' 
